[pytest]
DJANGO_SETTINGS_MODULE = billing_platform.settings
python_files = test_*.py
testpaths = tests
addopts = -v -rA --strict-markers --reuse-db --capture=tee-sys
filterwarnings =
    ignore::DeprecationWarning
